# Docker configuration backend
providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"

# API and dashboard configuration
api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: ":80"

log:
  level: INFO # Default Error. Available: DEBUG INFO WARN ERROR FATAL PANIC