services:

  ca-server:
    depends_on:
      ca-postgres:
        condition: service_healthy
    image: smallstep/step-ca:${greenhouse_version_ca_server}
    networks:
      greenhouse-infra:
    container_name: ${ENV}-ca
    scale: ${greenhouse_scale_ca}
    ports:
      - ${greenhouse_ca_port:-9000}:9000
    secrets:
      - step-ca_password
    environment:
      DOCKER_STEPCA_INIT_NAME: ${greenhouse_ca_config_name}
      DOCKER_STEPCA_INIT_DNS_NAMES: ${greenhouse_ca_config_dns_names}
      DOCKER_STEPCA_INIT_PROVISIONER_NAME: ${greenhouse_ca_config_provisioner_name:-admin}
      DOCKER_STEPCA_INIT_SSH: ${greenhouse_ca_config_ssh:-false}
      DOCKER_STEPCA_INIT_PASSWORD_FILE: /run/secrets/step-ca_password

      PGDATABASE: ${greenhouse_ca_postgres_db}
      PGUSER: ${greenhouse_ca_postgres_user}
      PGHOST: ca-postgres
      PGPORT: ${greenhouse_ca_postgres_port:-5432}
      PGPASSWORD : ${greenhouse_ca_postgres_password}
    volumes:
      - ${greenhouse_ca_volume_certs}:/home/step/certs
      - ${greenhouse_ca_volume_secrets:-${greenhouse_ca_main_volume_path}/secrets}:/home/step/secrets
      - ${greenhouse_ca_volume_config:-${greenhouse_ca_main_volume_path}/config}:/home/step/config
      - ${greenhouse_ca_volume_db:-${greenhouse_ca_main_volume_path}/db}:/home/step/db
      - ${greenhouse_ca_volume_main:-${greenhouse_ca_main_volume_path}/main}:/home/step
    healthcheck:
      test:
        - CMD-SHELL
        - step ca health
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s
    restart: unless-stopped
    labels:
      traefik.enable: false
      traefik.docker.network: none

  ca-postgres:
    image: postgres:${greenhouse_ca_postgres_version:-${greenhouse_postgres_general_version:-18.1}}
    container_name: ${ENV}-ca-postgres
    scale: ${greenhouse_scale_ca:-0}
    networks:
      greenhouse-infra:
    ports:
      - ${greenhouse_ca_postgres_port:-5432}:${greenhouse_ca_postgres_port:-5432}
    environment:
      PGPORT: ${greenhouse_ca_postgres_port:-5432}
      POSTGRES_DB: ${greenhouse_ca_postgres_db}
      PGUSER: ${greenhouse_ca_postgres_user} # Required for the healthcheck
      POSTGRES_USER: ${greenhouse_ca_postgres_user}
      POSTGRES_PASSWORD: ${greenhouse_ca_postgres_password}
    volumes:
      - ${greenhouse_ca_postgres_vol:-${VOLUMES_PATH}/step-ca-postgres}:/var/lib/postgresql
    restart: always
    healthcheck:
      test: 
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${PGUSER}
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    labels:
      traefik.enable: false

  # On the first run, remember to access to https://greenhouse_adguard_init_host to do the basics.
  # After https://greenhouse_adguard_host
  adguard:
    image: adguard/adguardhome:${greenhouse_version_adguard}
    networks:
      greenhouse-infra:
        ipv4_address: ${greenhouse_adguard_ip}
    container_name: ${ENV}-adguard
    scale: ${greenhouse_scale_adguard:-1}
    ports:
      - 53:53/tcp # Adguard DNS
      - 53:53/udp # Adguard DNS
    volumes:
      - ${greenhouse_adguard_volume_work:-${VOLUMES_PATH}/adguard/work}:/opt/adguardhome/work
      - ${greenhouse_adguard_volume_conf:-${VOLUMES_PATH}/adguard/conf}:/opt/adguardhome/conf
      - ${greenhouse_ca_volume_certs}:/opt/adguardhome/certs
    restart: unless-stopped
    labels:
      traefik.enable: true
      # ROUTER
      traefik.http.routers.adguard-ui.rule: Host(`${greenhouse_adguard_host:-adguard.${DOMAIN}}`)
      traefik.http.routers.adguard-ui.entrypoints: https
      traefik.http.routers.adguard-ui.service: adguard-ui
      traefik.http.routers.adguard-ui.tls.certresolver: greenhouse-resolver

      traefik.http.routers.adguard-ui-setup.rule: Host(`${greenhouse_adguard_init_host:-setup.${greenhouse_adguard_host}}`)
      traefik.http.routers.adguard-ui-setup.entrypoints: https
      traefik.http.routers.adguard-ui-setup.service: adguard-ui-setup
      traefik.http.routers.adguard-ui-setup.tls.certresolver: greenhouse-resolver
      # SERVICE
      traefik.http.services.adguard-ui.loadbalancer.server.port: 80
      traefik.http.services.adguard-ui-setup.loadbalancer.server.port: 3000
      # MIDDLEWARE
      traefik.http.routers.adguard-ui.middlewares: authentik@docker

secrets:
  step-ca_password:
    file: ${greenhouse_ca_secret_password_filepath:-${PWD}/secrets/step-ca_password}