networks:
  greenhouse-infra:
    driver: bridge
    ipam:
      config:
        - subnet: 42.42.42.0/24
          gateway: 42.42.42.42

services:

  traefik:
    image: traefik:3.5.0
    networks:
      greenhouse-infra:
        ipv4_address: 42.42.42.50
    container_name: ${ENV}-traefik
    volumes:
      - ./traefik/${ENV}/traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80             # HTTP
      - 53:53/tcp         # Adguard DNS
      - 53:53/udp         # Adguard DNS
      - 51820:51820/udp   # Wireguard VPN
    restart: unless-stopped
    labels:
      traefik.enable: true
      # ROUTER
      traefik.http.routers.dashboard.rule: Host(`test.traefik.localhost`)
      traefik.http.routers.dashboard.entrypoints: http
      traefik.http.routers.dashboard.service: api@internal
      # SERVICE
      # MIDDLEWARE
  
  whoami:
    image: traefik/whoami
    networks:
      greenhouse-infra:
        ipv4_address: 42.42.42.60
    scale: 1
    restart: always
    labels:
      traefik.enable: true
      # ROUTER
      traefik.http.routers.whoami.rule: Host(`test.traefik.localhost`) && Path(`/whoami`)
      traefik.http.routers.whoami.entrypoints: http
      traefik.http.routers.whoami.service: whoami-service
      # SERVICE
      traefik.http.services.whoami-service.loadbalancer.server.port: 80
      # MIDDLEWARE
      

  adguard:
    image: adguard/adguardhome:v0.107.65
    networks:
      greenhouse-infra:
        ipv4_address: 42.42.42.30
    container_name: ${ENV}-adguard
    volumes:
      - ./adguard/dev/work:/opt/adguardhome/work
      - ./adguard/dev/conf:/opt/adguardhome/conf
      - ./env/adguard/.dev.credentials:/opt/adguardhome/users-file
    restart: unless-stopped
    labels:
      traefik.enable: true
      # ROUTER
      traefik.http.routers.adguard.rule: Host(`test.adguard.localhost`)
      traefik.http.routers.adguard.entrypoints: http
      # SERVICE
      traefik.http.services.adguard.loadbalancer.server.port: 80
      # MIDDLEWARE

  wireguard:
    image: ghcr.io/wg-easy/wg-easy:15.1.0
    networks:
      greenhouse-infra:
        ipv4_address: 42.42.42.20
    container_name: ${ENV}-wireguard
    ports: 
      - "51820:51820/tcp"
    volumes:
      - ./wireguard/dev:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    environment:
      INSECURE: true
    restart: unless-stopped
    labels:
      traefik.enable: true
      # ROUTER
      traefik.http.routers.vpn-dashboard.rule: Host(`test.vpn.localhost`)
      traefik.http.routers.vpn-dashboard.entrypoints: http
      # SERVICE
      traefik.http.services.vpn-dashboard.loadbalancer.server.port: 51821
      # MIDDLEWARE

  nginx:
    image: nginx:1.25.3
    networks:
      greenhouse-infra:
        ipv4_address: 42.42.42.10
    container_name: ${ENV}-nginx-static-pages
    volumes:
      - ./nginx/${ENV}/conf:/etc/nginx/conf.d:ro
      - ./nginx/${ENV}/html:/usr/share/nginx/html
    restart: always
    labels:
      traefik.enable: true
      # ROUTER
      traefik.http.routers.nginx-static-pages.rule: Host(`test.localhost`)
      traefik.http.routers.nginx-static-pages.entrypoints: http
      # SERVICE
      traefik.http.services.nginx-static-pages.loadbalancer.server.port: 80
      # MIDDLEWARE
