
services:

  nginx:
    image: nginx:1.25.3
    networks:
      greenhouse-infra:
        ipv4_address: ${greenhouse_nginx_static_pages_ip}
    container_name: ${ENV}-nginx-static-pages
    scale: ${greenhouse_scale_nginx:-1}
    volumes:
      - ${greenhouse_nginx_static_pages_volume_conf:-${PWD}/nginx/${ENV}/conf}:/etc/nginx/conf.d:ro
      - ${greenhouse_nginx_static_pages_volume_html:-${PWD}/nginx/${ENV}/html}:/usr/share/nginx/html
    restart: always
    labels:
      traefik.enable: true
      # ROUTER
      traefik.http.routers.nginx-static-pages.rule: Host(`${greenhouse_nginx_static_pages_host}`)
      traefik.http.routers.nginx-static-pages.entrypoints: https
      traefik.http.routers.nginx-static-pages.tls.certresolver: greenhouse-resolver
      # SERVICE
      traefik.http.services.nginx-static-pages.loadbalancer.server.port: 80
      # MIDDLEWARE

