networks:
  greenhouse-infra:
    driver: bridge
    ipam:
      config:
        - subnet: 42.42.42.0/24
          gateway: 42.42.42.42

services:

  traefik:
    image: traefik:3.5.0
    networks:
      greenhouse-infra:
        ipv4_address: 42.42.42.50
    volumes:
      - ./traefik/${ENV}/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80         # HTTP
      - 53:53/tcp     # Adguard DNS
      - 53:53/udp     # Adguard DNS
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      
      traefik.http.routers.dashboard.service: "api@internal"
      traefik.http.routers.dashboard.rule: "PathPrefix(`/traefik`) || PathPrefix(`/traefik/dashboard/`)"
      traefik.http.routers.dashboard.entrypoints: "http"
  
  whoami:
    image: traefik/whoami
    networks:
      greenhouse-infra:
        ipv4_address: 42.42.42.60
    restart: always
    labels:
      traefik.enable: "true"

      traefik.http.services.whoami.loadbalancer.server.port: "80"
      
      traefik.http.routers.whoami.rule: "PathPrefix(`/whoami`)"
      traefik.http.routers.whoami.entrypoints: "http"

  adguard:
    image: adguard/adguardhome:v0.107.65
    networks:
      greenhouse-infra:
        ipv4_address: 42.42.42.30
    volumes:
      - ./adguard/dev/work:/opt/adguardhome/work
      - ./adguard/dev/conf:/opt/adguardhome/conf
    restart: unless-stopped
    labels:
      traefik.enable: "true"

      traefik.http.services.adguard.loadbalancer.server.port: "80"
      traefik.http.routers.adguard.rule: "PathPrefix(`/adguard`)"
      traefik.http.routers.adguard.entrypoints: "http"

      traefik.http.middlewares.adguard-stripprefix.stripprefix.prefixes: "/adguard"
      traefik.http.routers.adguard.middlewares: "adguard-stripprefix"

  nginx:
    image: nginx:1.25.3
    networks:
      greenhouse-infra:
        ipv4_address: 42.42.42.10
    volumes:
      - ./nginx/${ENV}/conf:/etc/nginx/conf.d:ro
      - ./nginx/${ENV}/html:/usr/share/nginx/html
    restart: always
    labels:
      traefik.enable: "true"

      traefik.http.services.nginx-index.loadbalancer.server.port: "80"
      traefik.http.routers.nginx-index.rule: "PathPrefix(`/`)"
      traefik.http.routers.nginx-index.entrypoints: "http"