networks:
  greenhouse-infra:
    driver: bridge
    ipam:
      config:
        - subnet: 42.42.42.0/24
          gateway: 42.42.42.42

services:
  noip-sync:
    image: noipcom/noip-duc:3.3.0
    env_file: ./env/noip/.dev.env
    restart: always

  adguard:
    image: adguard/adguardhome:v0.107.63
    networks:
      greenhouse-infra:
        ipv4_address: 42.42.42.30
    volumes:
      - ./adguard/dev/work:/opt/adguardhome/work
      - ./adguard/dev/conf:/opt/adguardhome/conf
    ports:
      - 53:53/tcp 
      - 53:53/udp

      - 8080:80/tcp
      - 3000:3000/tcp
    restart: unless-stopped

  wireguard:
    image: ghcr.io/wg-easy/wg-easy:15.1.0
    networks:
      greenhouse-infra:
        ipv4_address: 42.42.42.20
    volumes:
      - ./wireguard/dev:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    environment:
      INSECURE: true
    restart: unless-stopped

  nginx:
    image: nginx:1.25.3
    networks:
      greenhouse-infra:
        ipv4_address: 42.42.42.10
    ports:
      - 80:80
    volumes:
      - ./nginx/dev/conf:/etc/nginx/conf.d:ro
      - ./nginx/dev/html:/usr/share/nginx/html
    restart: always

  teamspeak:
    image: teamspeak:3.13.7
    networks:
      greenhouse-infra:
        ipv4_address: 42.42.42.40
    ports:
      - 9987:9987/udp         # Voice
      - 127.0.0.1:10011:10011 # ServerQuery
      - 127.0.0.1:30033:30033 # File transfer
    env_file: ./env/teamspeak/.dev.env
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: teamspeak-db
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    volumes:
      - ./teamspeak/server:/var/ts3server
    restart: always
    depends_on:
      teamspeak-db:
        condition: service_started
    
  teamspeak-db:
    image: mariadb:12.1.1-noble-rc
    networks:
      - greenhouse-infra
    env_file: ./env/teamspeak/.dev.env
    environment:
      MYSQL_DATABASE: teamspeak
    volumes:
      - ./teamspeak/mariadb:/var/lib/mysql:z
    restart: always
