---
# Playbook to update and upgrade packages on Debian/Ubuntu systems
- name: Update and upgrade all Debian/Ubuntu systems
  hosts: linux  # Change this to target specific hosts or groups
  vars_files:
    - ../inventory/host_vars/vault.yml
  become: yes  # Ensures that the playbook is run as a sudo user
  tasks:

    - name: Update apt package index
      apt:
        update_cache: yes  # Equivalent to running 'apt update'
    
    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist  # Equivalent to running 'apt upgrade'

    - name: Autoremove unnecessary packages
      apt:
        autoremove: yes

    - name: Clean up cached packages
      apt:
        autoclean: yes