---
- name: Ping Linux Machines
  hosts: rpi
  vars_files:
    - /greenhouse/ansible/config/secrets/vault.yml
  become: false
  gather_facts: false
  tasks:
    - name: Printing some Debug Information
      debug:
        msg:
          - "Host {{ ansible_host }}"
          - "Port {{ ansible_port }}"
    - name: test connection
      ping:
- name: Ping Windows Machines
  hosts: w3070
  vars_files:
    - /greenhouse/ansible/config/secrets/vault.yml
  become: false
  gather_facts: false
  tasks:
    - name: tests connection
      ansible.windows.win_ping: