---
- name: Ping Windows Machines
  hosts: w3070
  host_vars:
    - /greenhouse/ansible/config/secrets/vault.yml
  become: false
  gather_facts: false
  tasks:
    - name: tests connection
      ansible.windows.win_ping:
- name: Ping Linux Machines
  hosts: rpi
  host_vars:
    - /greenhouse/ansible/config/secrets/vault.yml
  become: false
  gather_facts: false
  tasks:
    - name: test connection
      ping: