volumes:
  teamspeak-server:
  teamspeak-data-db:

services:

  teamspeak:
    image: teamspeak:3.13.7
    ports:
      - 9987:9987/udp        
      - 127.0.0.1:10011:10011
      - 127.0.0.1:30033:30033
    env_file: ./env/teamspeak/.env
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: teamspeak-db
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    volumes:
      - teamspeak-server:/var/ts3server
    restart: always
    depends_on:
      teamspeak-db:
        condition: service_started
    
  teamspeak-db:
    image: mariadb:12.1.1-noble-rc
    env_file: ./env/teamspeak/.env
    environment:
      MYSQL_DATABASE: teamspeak
    volumes:
      - teamspeak-data-db:/var/lib/mysql:z
    restart: always